version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432,
      DB_NAME: group_peer_evals_db
      DB_USER: user
      DB_PASSWORD: pass
      # DATABASE_URL: postgres://user:pass@postgres:5432/group_peer_evals_db 
      LTI_CONSUMER_KEY: foo
      LTI_SHARED_SECRET: bar
      CANVAS_ACCESS_TOKEN: 1726~UacZkl2ndcdgLx9VXUZkWk8L3i3DjupW2NvYCbJD0L8wltBkPmCgRVp9vsRfm4gc
      NODE_ENV: development 
      PORT: 3000
    ports:
      - "3000:3000"
    # command: npm start 
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    container_name: postgres
    image: postgres:12
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: group_peer_evals_db